# Generated by Django 4.2.2 on 2023-06-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0003_myuser_country_code_cart_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
