# Generated by Django 4.2.2 on 2023-06-16 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0006_cartitem_alter_cart_user_delete_cart_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="city",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="myuser",
            name="country",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_number", models.CharField(editable=False, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("PR", "Processing"),
                            ("S", "Shipped"),
                            ("D", "Delivered"),
                        ],
                        default="P",
                        max_length=2,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CC", "Credit Card"),
                            ("VS", "Visa"),
                            ("MC", "Master Card"),
                            ("COD", "Cash On Delivery"),
                            ("VF", "Vodafone"),
                            ("OG", "Orange"),
                            ("WE", "Wepay"),
                            ("PP", "Paypal"),
                            ("BT", "Bank Transfer"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="frontend.cart"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
