# Generated by Django 4.2.2 on 2023-06-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0007_myuser_city_myuser_country_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="ordered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="ordered_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.FloatField(default=0),
        ),
    ]
