# Generated by Django 4.2.2 on 2023-06-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0008_cart_ordered_order_ordered_at_product_discount_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
