# Generated by Django 4.2.2 on 2023-06-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0009_alter_product_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=15)),
                ("discount", models.FloatField()),
            ],
        ),
    ]
