# Generated by Django 4.2.2 on 2023-06-20 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0010_promocode"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="frontend.promocode",
            ),
        ),
        migrations.AddField(
            model_name="promocode",
            name="max_discount",
            field=models.FloatField(default=100),
        ),
    ]
