# Generated by Django 4.2.2 on 2023-06-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0011_cart_coupon_promocode_max_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="shipping_cost",
            field=models.DecimalField(decimal_places=2, default=25.99, max_digits=10),
        ),
    ]
