# Generated by Django 4.2.2 on 2023-06-21 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0014_order_address_order_first_name_order_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="anonymous_cart",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="frontend.cart",
            ),
        ),
    ]
