# Generated by Django 4.2.2 on 2023-06-21 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0015_order_anonymous_cart_alter_order_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.CreateModel(
            name="neword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CartItem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frontend.cartitem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ManyToManyField(related_name="items", to="frontend.cart"),
        ),
    ]
