# Generated by Django 4.2.2 on 2023-06-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0017_orderitem_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(default="", max_length=100),
        ),
    ]
