# Generated by Django 4.2.2 on 2023-06-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0019_order_final_price_alter_order_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="final_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
