# Generated by Django 4.2.2 on 2023-06-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0020_alter_order_final_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="customized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(default="00", max_length=100),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="customized",
            field=models.BooleanField(default=False),
        ),
    ]
