# Generated by Django 4.2.2 on 2023-06-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0021_cartitem_customized_order_phone_orderitem_customized"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=100),
        ),
    ]
