# Generated by Django 4.2.2 on 2023-06-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0022_alter_order_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="0", editable=False, max_length=32),
        ),
    ]
