# Generated by Django 4.2.2 on 2023-06-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0023_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
