# Generated by Django 4.2.2 on 2023-06-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0025_order_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CC", "Credit Card"),
                    ("VS", "Visa"),
                    ("MC", "Master Card"),
                    ("COD", "Cash On Delivery"),
                    ("VF", "Vodafone"),
                    ("OG", "Orange"),
                    ("WE", "Wepay"),
                    ("PP", "Paypal"),
                    ("BT", "Bank Transfer"),
                ],
                default="Credit Card",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_cost",
            field=models.DecimalField(decimal_places=2, default=25.99, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("PR", "Processing"),
                    ("S", "Shipped"),
                    ("D", "Delivered"),
                ],
                default="P",
                max_length=2,
            ),
        ),
    ]
