# Generated by Django 4.2.2 on 2023-06-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0026_order_payment_method_order_shipping_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="applied_coupons",
            field=models.ManyToManyField(
                blank=True, related_name="Applied_Coupons", to="frontend.promocode"
            ),
        ),
    ]
