# Generated by Django 4.2.2 on 2023-06-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0027_cart_applied_coupons"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="label",
            field=models.CharField(
                choices=[("NEW", "primary"), ("BEST Seller", "secondary"), ("N", "")],
                default="N",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("S", "Shirt"), ("SW", "Sport wear"), ("OW", "Outwear")],
                max_length=2,
            ),
        ),
    ]
