# Generated by Django 4.2.2 on 2023-06-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0029_alter_product_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("P", "Placed"), ("S", "Shipped"), ("D", "Delivered")],
                default="P",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("M", "Men"),
                    ("W", "Women"),
                    ("K", "Kids"),
                    ("A", "Accessories"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="subcategory",
            field=models.CharField(
                choices=[("S", "Shirt"), ("SW", "Sport wear"), ("OW", "Outwear")],
                default="",
                max_length=50,
            ),
        ),
    ]
