# Generated by Django 3.2.10 on 2023-06-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0030_alter_order_status_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='frontend/static/images'),
        ),
    ]
