# Generated by Django 3.2.10 on 2023-06-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0033_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('NEW', 'primary'), ('BEST Seller', 'secondary'), ('', 'N')], default='', max_length=11),
        ),
    ]
