# Generated by Django 3.2.10 on 2023-06-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0039_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='color_id',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
