# Generated by Django 3.2.10 on 2023-06-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0042_auto_20230626_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='favorites',
            field=models.ManyToManyField(to='frontend.Product'),
        ),
    ]
